service:
  name: why-unit-tests

spring:
  application:
    name: ${service.name}
  profiles:
    active: secret,config
  jpa:
    properties:
      hibernate:
        default_schema: ${service.name}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:${pgsql.url}/${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: ${spring.application.name}-dba
    hikari:
      schema: ${service.name}
      maximum-pool-size: 12
      minimum-idle: 2
      idle-timeout: 1800000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 3000
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    schemas: ${service.name}